spring:
  datasource:
    url: <DB_URL>
    username: <USERNAME>
    password: <PASSWORD>
server:
  error:
    include-message: always
    include-binding-errors: always
frontend:
  url: <FRONTEND_URL>
